keycloak:
  server-url: http://localhost:9999
  realm: spring-app-realm
  client-id: spring-boot-app
  client-secret: H9suB1PQfzvvJgEYjXqNuSqU2cxubSrY

file:
  client-path: /files
  storage-location: /Users/kk/Engineering/ite-images/
  base-url: http://localhost:${server.port}/${file.client-path}/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/spring-app-realm
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  application:
    name: product-api-demo
  # jpa, postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_db
    username: postgres
    password: sancluvspostgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update     # create | update | none
    show-sql: true          # log generated SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080